AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CatchPokemon

Globals:
  Function:
    Timeout: 10

Resources:
  CatchPokemonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: catch-pokemon
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        TesteRealizado:
          Type: SQS
          Properties:
            Queue: YOUR-SQS-ARN-HERE
            BatchSize: 1
      Environment:
        Variables:
          env: LOCAL









